version: '3'

services:

  hello-lucas:
    build:
      context: ./docker
    container_name: hello-lucas
    hostname: hello-lucas
    command: yarn dev
    working_dir: /app
    tty: true
    env_file: .env
    ports:
    - 8080:8080
    volumes:
    - .:/app:delegated
    - home:/home/node

volumes:
  home:
